### ISSUE TITLE
Unknown error archiving messages

### ISSUE THREAD

**Issue by the-moog** [ArchiveTeam/yahoo-group-archiver#56]
I get this error, any clues?

```
2020-10-16 15:11:17.111 CEST ERROR archive_email Unknown error archiving messages
Traceback (most recent call last):
  File "./yahoo.py", line 136, in archive_email
    init_messages = yga.messages()
  File "/home/jasonm/yahoo-group-archiver/yahoogroupsapi.py", line 188, in get_json
    raise NotFound()
yahoogroupsapi.NotFound
```

**Comment by the-moog** [comment]
More info
API https://groups.yahoo.com/api/v1/groups/concatenative/ works
API https://groups.yahoo.com/api/v1/groups/concatenative/messages is 404
So hopefully the API has changed and we can find out how or it has been disabled completly rendering this tool useless

**Comment by aresnick** [comment]
I'm also running into this issue; any thoughts on how to address it?
