### ISSUE TITLE
Handle Error 500 on attempted message download

### ISSUE THREAD

**Issue by d235j** [ArchiveTeam/yahoo-group-archiver#8]
Sometimes the Yahoo API returns an Error 500 for a message (data corruption on the servers?) This is not currently handled for the raw endpoint.

**Comment by ewanuno** [comment]
looks like this:

`* Fetching raw message #3382 of 9070
Exception raised on uri: https://groups.yahoo.com/api/v1/groups/Mirage-Net/messages/3382/raw
{"ygPerms":{"resourceCapabilityList":[{"resourceType":"GROUP","capabilities":[{"name":"READ"},{"name":"WELCOME_MSG"}]},{"resourceType":"PHOTO","capabilities":[{"name":"READ"},{"name":"UPLOAD"},{"name":"UPLOADTEMP"}]},{"resourceType":"FILE","capabilities":[{"name":"READ"},{"name":"CREATE"}]},{"resourceType":"MEMBER","capabilities":[{"name":"READ"}]},{"resourceType":"LINK","capabilities":[{"name":"CREATE"},{"name":"READ"}]},{"resourceType":"CALENDAR","capabilities":[]},{"resourceType":"DATABASE","capabilities":[{"name":"READ"},{"name":"CREATE"},{"name":"READ_DATA"}]},{"resourceType":"POLL","capabilities":[{"name":"READ"},{"name":"VOTE"},{"name":"CREATE"}]},{"resourceType":"MESSAGE","capabilities":[{"name":"CREATE"},{"name":"READ"}]},{"resourceType":"PENDING_MESSAGE","capabilities":[]},{"resourceType":"ATTACHMENTS","capabilities":[{"name":"READ"}]},{"resourceType":"PHOTOMATIC_ALBUMS","capabilities":[{"name":"READ"},{"name":"UPLOAD"}]},{"resourceType":"MEMBERSHIP_TYPE","capabilities":[{"name":"READ"}]},{"resourceType":"POST","capabilities":[{"name":"READ"},{"name":"CREATE"}]},{"resourceType":"PIN","capabilities":[{"name":"DELETE"},{"name":"UPDATE"},{"name":"READ"},{"name":"CREATE"}]}],"subStatus":"NORMAL","groupUrl":"groups.yahoo.com","intlCode":"us"},"ygError":{"hostname":"gapi3.grp.bf1.yahoo.com","httpStatus":500,"errorMessage":"Internal error: Error during message fetch","errorCode":1001,"sid":"SID:YHOO:groups.yahoo.com:6d7cde5513853683bf1ca9fd9bd29f15:0"}}
Traceback (most recent call last):
  File "./yahoo.py", line 468, in <module>
    archive_email(yga, save=(not args.no_save), html=args.html)
  File "./yahoo.py", line 64, in archive_email
    raw_json = yga.messages(id, 'raw')
  File "/Users/ewancolsell/Documents/GitHub/archiveteamyahoo-group-archiver/yahoogroupsapi.py", line 96, in get_json
    raise e
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://groups.yahoo.com/api/v1/groups/Mirage-Net/messages/3382/raw`
