### ISSUE TITLE
Error 400

### ISSUE THREAD

**Issue by ewanuno** [ArchiveTeam/yahoo-group-archiver#9]
Traceback (most recent call last):
  File "./yahoo.py", line 471, in <module>
    archive_files(yga)
  File "./yahoo.py", line 160, in archive_files
    yga.download_file(path['downloadURL'], f)
  File "/Users/ewancolsell/Documents/GitHub/archiveteamyahoo-group-archiver/yahoogroupsapi.py", line 71, in download_file
    r.raise_for_status()
  File "/Library/Python/2.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://xa.yimg.com/df/miragelives/Mdisk.rar?token=p5DU3g8LNaEMCoEwpzVF1vTkeYzs9yqtmQLl7d3kbhm8cIW1XuafEsjbIkHHa3-zFHTJXRmSpHny19lRJVOasoh7tFHwF1aR&type=download

**Comment by ewanuno** [comment]
this happens every time with the same file. it retries 5 times then exits.
